on:
  push:
    branches: [main, master, test]
  pull_request:
    branches: [main, master]

name: duckdb-test

jobs:
  Postgres-test:
    if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.1
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        TESTTHAT_CPUS : 1

    name: duckdb-test

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Run tests on duckdb
        run: R -e 'devtools::install(); withr::with_envvar(new = c("CI_TEST_DB" = "duckdb", "TESTTHAT_CPUS" = 1), testthat::test_local())'


