# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# the purpose of this workflow is to run R CMD CHECK without installing suggested packages
# CRAN will check this

on:
  push:
    branches: [main, master, test]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check-hard-deps:
    # if: github.repository == 'darwin-eu-dev/CDMConnector' || github.repository == 'darwin-eu/CDMConnector'
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      CI_TEST_DB: duckdb
      TESTTHAT_CPUS : 1

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"' # install only imports, depends, and linking to (hard dependencies)
          extra-packages: any::rcmdcheck
          needs: check

      - name: List contents of home directory
        run: |
            print("Home directory content before R check")
            print(list.files(path.expand("~")))
        shell: Rscript {0}

      - name: Add options to .Rprofile
        run: |
            echo "options(rmarkdown.html_vignette.check_title = FALSE)" >> ~/.Rprofile
        shell: bash

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: 'c("--no-manual", "--as-cran", "--no-build-vignettes", "--ignore-vignettes")'
          error-on: '"error"'

      -  name: List contents of home directory after R check
         run: |
            print("Home directory content after R check. Should be the same as before R check.")
            print(list.files(path.expand("~")))
         shell: Rscript {0}

